theme: jekyll-theme-cayman

permalink: pretty

baseurl: https://github.com/AlexRogalskiy/android-patterns
title: Scala Design Patterns
description: Explores different architectural concepts and design principles for Scala applications

author: Alexander Rogalskiy

docs: https://github.com/AlexRogalskiy/scala-patterns/wiki
blog: https://alexrogalskiy.github.io/
