name: Latest articles and podcasts

on:
  workflow_dispatch:
  schedule:
    # Runs every day
    - cron: '0 1 * * *'

jobs:
  update-readme-with-posts:
    name: Update this repo's README with latest articles and podcasts on Scala
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "10"
          comment_tag_name: "REDDIT-POST-LIST"
          feed_list: "https://www.reddit.com/r/scala/.rss"
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "10"
          comment_tag_name: "INFOWORLD-POST-LIST"
          feed_list: "https://www.infoworld.com/category/scala/index.rss"
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "10"
          comment_tag_name: "REDHAT-POST-LIST"
          feed_list: "https://developers.redhat.com/blog/tag/scala/feed/"
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "10"
          comment_tag_name: "AKKA-POST-LIST"
          feed_list: "https://akka.io/atom.xml"
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "10"
          comment_tag_name: "LIHAOYI-POST-LIST"
          feed_list: "https://www.lihaoyi.com/feed.xml"
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "10"
          comment_tag_name: "SCALALANG-POST-LIST"
          feed_list: "https://www.scala-lang.org/feed/blog.xml"
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "10"
          comment_tag_name: "SCALAC-POST-LIST"
          feed_list: "https://scalac.io/blog/feed/"